### ISSUE TITLE
No way to specify system properties for the test

### ISSUE THREAD

**Issue by KarolS** [zalando/zester#1]
Most of my unit tests require to be run in a VM with correct system properties. For Application and JUnit run configurations, there's a "VM options" field, where I add several "-Dkey=value" options as needed. Zester has no such functionality, thus limiting me to using it only working with tests that are don't require those properties.

**Comment by semonte** [comment]
Sounds reasonable, I will add "VM options" field to Zester configuration.

**Comment by semonte** [comment]
Fixed by 3be0ecc397bc7bc4cb21c2b5ad0ad4748329d271.

**Comment by KarolS** [comment]
Thanks, it appears to work perfectly.
