### ISSUE TITLE
Excluding multiple classes

### ISSUE THREAD

**Issue by Nicte** [zalando/zester#5]
Hi,

I am trying to exclude multiple classes from being analyzed but I don't manage to do so. According to PIT documentation (http://pitest.org/quickstart/commandline/) I should use the --excludeClasses parameter and pass a comma separated array of values. I am trying this in Zester's "Program arguments":

--excludedClasses
com.module.app.accounting.backend.persistence.*, com.module.app.accounting.backend.util.*

But the result is that only the first package gets excluded and the second one its included. If I revert the order, happens exactly the same. I have tried surrounding it with "" but it has no effect

Am I doing something wrong or is there an actual issue with Zester's argument parsing?

Thanks,
Nicte

**Comment by semonte** [comment]
Hi @Nicte 

Thanks for reporting the issue, I will take a look at this to check is it Zester or PIT.

**Comment by Nicte** [comment]
Hi @semonte 

By any chance, did you took a look at this? Is there any workaround for it maybe?

**Comment by semonte** [comment]
Hi @Nicte sorry for taking such a long time to reply. I checked the issue. It seems that if you have a space before the class or package name things will not work.

Does not work:
`--excludedClasses com.package.Class1, com.package.Class2`

Works:
`--excludedClasses com.package.Class1,com.package.Class2`

In my opinion this should actually be handled in PIT. Can you verify that the `excludedClasses` works for you if you do not have spaces?

**Comment by Nicte** [comment]
Hi @semonte,

Thanks for your reply. I can confirm you that removing the space after the comma makes it work as expected.

I think this is workaround is good enough and hopefully, now it will be documented with this issue in case someone else has the same problem in the future.

Thanks!
